module.exports={
  SIGNUP : 'User signup successfully.',
  LOGIN  : 'User login successfully.',
  USER_PROFILE:'User profile data.',
  USER_PROFILE_UPDATE:'User profile updated successfully.',
  CHANGE_PASSWORD:'Changed password successfully.',
  UNAUTHORIZED:'User is not authrorised.',
  IN_VALID_PASSWORD:'Your Old password is wrong,Please enter a valid Password.',
  MISMATCH_PASSWORD:'Password and confirm password didnot match.', 
  EMAIL_OR_PASSWORD_MISMATCH:'Email or password is incorrect. Please enter valid credentials.',
  USER_LOGOUT:'User logout successfully.', 
  DATA_SAVE:'Data saved successfully.',
  DATA_UPDATED: 'Data updated successfully.',
  DATA_LIST: 'Data list.',
  FORGOT_PASSWORD:'Forgot password send to you email id.',
  SAVE_CONTACTUS:'Contact us data save successfully.',
  CONTACTUS_LISTS :'Contact lists.',
  ORDERS_LISTS :'Order lists.',
  INQUIRY_LISTS :'Inquiry lists.',
  USER_LISTS:'User lists.',
  LOCATION_LIST : 'Location list.',
  COUNTRY_LIST : 'Country list.',
  SERVER_ERROR :'Internal server error',
  CAPACITY_LIST : 'Capacity list.',
  TYPE_LIST : 'Type list.',
  CATEGORY_LIST : 'Category list.',
  ADD_PRODUCT : 'Add products successfully.',
  EDIT_PRODUCT :'Edit product successfully.',
  UPDATE_PRODUCT:'Update product successfully.',
  PRODUCT_DETAILS:'Products details.',
  CHANGE_ORDER_STATUS:'Order status changed successfully.',
  ORDER_PLASED: 'Order placed successfully'
};